services:
- type: pserv
  name: mysql
  plan: standard
  env: docker
  autoDeploy: true
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 0.5
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: kreta
  - key: MYSQL_USER
    value: kretamysql
  - key: MYSQL_PASSWORD
    value: kreta
  - key: MYSQL_ROOT_PASSWORD
    value: kreta